# Generated by Django 5.2.1 on 2025-06-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('image_path', models.URLField()),
                ('categories', models.ManyToManyField(to='app.category')),
                ('merchandise', models.ManyToManyField(to='app.merchandise')),
                ('servers', models.ManyToManyField(to='app.server')),
            ],
        ),
    ]
