# Generated by Django 5.2.1 on 2025-06-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='reseller_category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchandise',
            name='reseller_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
