# Generated by Django 5.2.1 on 2025-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merchandise_enabled_merchandise_reseller_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='merchandise',
            field=models.ManyToManyField(blank=True, to='app.merchandise'),
        ),
        migrations.AlterField(
            model_name='game',
            name='servers',
            field=models.ManyToManyField(blank=True, to='app.server'),
        ),
    ]
