# Generated by Django 5.2.1 on 2025-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_game_merchandise_alter_game_servers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='merchandise',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='game',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='server',
            field=models.CharField(max_length=100),
        ),
    ]
