# Generated by Django 5.2.1 on 2025-06-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_game_merchandise_merchandise_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='inputs',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
