# Generated by Django 5.2.1 on 2025-06-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_game_inputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='server',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
