# Generated by Django 5.2.1 on 2025-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_merchandise_server_alter_merchandise_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='inputs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
