# Generated by Django 5.2.1 on 2025-06-04 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0004_merchandise_enabled_merchandise_reseller_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('server_response', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('merchandise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.merchandise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.telegramuser')),
            ],
        ),
    ]
