# Generated by Django 5.2.1 on 2025-06-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='inputs',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
